[phases.setup]
nixPkgs = ["nodejs_20", "python3"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx @nestjs/cli@latest build"
]

[start]
cmd = "node dist/main"
